-- Retrieve all records from the orders table
SELECT * FROM orders;

-- Count the total number of orders placed
SELECT COUNT(*) FROM `order`;

-- Get a list of all unique restaurant IDs
SELECT DISTINCT `Restaurant ID` FROM `order`;

-- Find the highest single order amount
SELECT MAX(`Order Amount`) FROM `order`;

-- Calculate the total revenue generated from all orders
SELECT SUM(`Order Amount`) FROM `order`;

-- Calculate the average order amount per transaction
SELECT AVG(`Order Amount`) FROM `order`;

-- Calculate the average delivery time across all orders
SELECT AVG(`Delivery Time Taken (mins)`) AS AvgDeliveryTime
FROM `order`;

-- Count total number of orders placed using each payment method
SELECT `Payment Mode`, 
COUNT(*) AS TotalOrders
FROM `order`
GROUP BY `Payment Mode`
ORDER BY TotalOrders DESC;

-- Calculate total revenue generated by each restaurant
SELECT `Restaurant ID`, 
SUM(`Order Amount`) AS TotalRevenue
FROM `order`
GROUP BY `Restaurant ID`
ORDER BY TotalRevenue DESC;

-- Find the average delivery time experienced by each customer
SELECT `Customer Name`,
AVG(`Delivery Time Taken (mins)`) AS AvgDeliveryTime
FROM `order`
GROUP BY `Customer Name`
ORDER BY AvgDeliveryTime ASC;

-- Calculate total revenue generated through each payment method
SELECT `Payment Mode`,
SUM(`Order Amount`) AS TotalRevenue
FROM `order`
GROUP BY `Payment Mode`
ORDER BY TotalRevenue DESC;

-- Get total orders placed and total amount spent by each customer
SELECT `Customer Name`,
COUNT(*) AS TotalOrders,
SUM(`Order Amount`) AS TotalSpent
FROM `order`
GROUP BY `Customer Name`
ORDER BY TotalSpent DESC;

-- Find the average delivery time for orders grouped by payment method
SELECT `Payment Mode`,
AVG(`Delivery Time Taken (mins)`) AS AvgDeliveryTime
FROM `order`
GROUP BY `Payment Mode`
ORDER BY AvgDeliveryTime ASC;

-- Identify customers who frequently place high-value orders (above ₹1000)
SELECT `Customer Name`,
COUNT(*) AS HighestOrders,
AVG(`Order Amount`) AS AvgHighAmount
FROM `order`
WHERE `Order Amount` > 1000
GROUP BY `Customer Name`
ORDER BY HighestOrders DESC;

-- Get the top 5 customers by total amount spent
SELECT `Customer Name`,
SUM(`Order Amount`) AS TotalSpent
FROM `order`
GROUP BY `Customer Name`
ORDER BY TotalSpent DESC
LIMIT 5;

-- Get the top 5 customers by highest average food rating
SELECT `Customer Name`,
AVG(`Customer Rating-Food`) AS Avgrating 
FROM `order`
GROUP BY `Customer Name`
ORDER BY Avgrating DESC
LIMIT 5;

-- Get the top 5 most frequent customers by number of orders
SELECT `Customer Name`,
COUNT(*) AS TotalOrders
FROM `order`
GROUP BY `Customer Name`
ORDER BY TotalOrders DESC
LIMIT 5;

-- Get top 5 customers with their total orders, total spend, and average order value
SELECT `Customer Name`,
COUNT(*) AS TotalOrders,
SUM(`Order Amount`) AS TotalSpent,
AVG(`Order Amount`) AS AvgSpent
FROM `order`
GROUP BY `Customer Name`
ORDER BY TotalSpent DESC
LIMIT 5;

-- Detailed summary of top 10 loyal customers (with at least 2 orders) including spending, delivery time, and food rating
SELECT `Customer Name`,
COUNT(*) AS TotalOrders,
SUM(`Order Amount`) AS TotalSpent,
AVG(`Order Amount`) AS AvgSpent,
AVG(`Delivery Time Taken (mins)`) AS AvgDeliveryTime,
AVG(`Customer Rating-Food`) AS AvgFoodRating
FROM `order`
GROUP BY `Customer Name`
HAVING COUNT(*) >= 2
ORDER BY TotalSpent DESC
LIMIT 10;
